import Seo from '../components/Seo.jsx'
import Hero from '../components/Hero.jsx'
import About from '../components/About.jsx'
import Services from '../components/Services.jsx'
import Pricing from '../components/Pricing.jsx'
import FastTrack from '../components/FastTrack.jsx'
import Activities from '../components/Activities.jsx'
import MultiDay from '../components/MultiDay.jsx'
import Testimonials from '../components/Testimonials.jsx'
import FAQ from '../components/FAQ.jsx'
import Contact from '../components/Contact.jsx'
import { useLanguage } from '../context/LanguageContext.jsx'
import { business } from '../data/business.js'
export default function Home() { const { lang } = useLanguage(); const jsonLd = { '@context': 'https://schema.org', '@type': 'LocalBusiness', name: business.name, url: business.siteUrl, logo: `${business.siteUrl}/logo.png`, telephone: business.phone, email: business.email, areaServed: business.country, sameAs: [business.instagram, business.facebook, business.tripAdvisorUrl], address: { '@type': 'PostalAddress', streetAddress: business.address, addressLocality: business.city, addressCountry: 'MA' } }; return <><Seo title="Atlas Drive | Luxury Touristic Transport in Morocco" description="Atlas Drive — premium private transfers, city tours, desert excursions and multi-day journeys across Morocco. Marrakech-based, multilingual drivers, 24/7 WhatsApp booking." path="/"><script type="application/ld+json">{JSON.stringify(jsonLd)}</script></Seo><Hero lang={lang} /><About lang={lang} /><Services lang={lang} /><Pricing lang={lang} /><FastTrack lang={lang} /><Activities lang={lang} /><MultiDay lang={lang} /><Testimonials lang={lang} /><FAQ lang={lang} /><Contact lang={lang} /></> }
