import { useParams } from 'react-router-dom'
import { getService } from '../data/services.js'
import Seo from '../components/Seo.jsx'
import Breadcrumbs from '../components/Breadcrumbs.jsx'
import IncludedList from '../components/IncludedList.jsx'
import RelatedRoutes from '../components/RelatedRoutes.jsx'
import BookingForm from '../components/BookingForm.jsx'
import CtaBand from '../components/CtaBand.jsx'
export default function ServiceDetail() { const service = getService(useParams().slug); if (!service) return <NotFound />; return <><Seo title={service.seo.title} description={service.seo.description} path={`/services/${service.slug}`} /><Breadcrumbs items={[{label:'Services',to:'/services'},{label:service.title}]} /><main className="max-w-5xl mx-auto px-5 md:px-8 pb-20"><section className="bg-ink text-sand rounded-lg p-8 md:p-14 mb-14"><p className="font-mark text-gold text-xs tracking-widest2 uppercase mb-4">Atlas Drive service</p><h1 className="font-display text-5xl">{service.h1}</h1><p className="text-sand/70 mt-5 max-w-2xl leading-relaxed">{service.intro}</p></section><section className="space-y-4 mb-14">{service.body.map((paragraph) => <p key={paragraph} className="text-ink/70 leading-relaxed">{paragraph}</p>)}</section><section className="mb-14"><h2 className="font-display text-4xl text-ink mb-6">What’s included</h2><IncludedList keys={service.whatIsIncluded} /></section><section className="mb-14"><h2 className="font-display text-4xl text-ink mb-6">Book this service</h2><BookingForm /></section><section className="mb-14"><h2 className="font-display text-4xl text-ink mb-6">Related routes</h2><RelatedRoutes slugs={service.relatedRoutes} /></section><section><h2 className="font-display text-4xl text-ink mb-6">Questions</h2><div className="space-y-3">{service.faqs.map((faq) => <details key={faq.q} className="border border-ink/15 rounded-lg p-5"><summary className="font-display text-xl cursor-pointer">{faq.q}</summary><p className="text-sm text-ink/70 mt-3">{faq.a}</p></details>)}</div></section></main><CtaBand /></> }
function NotFound() { return <section className="min-h-[70vh] pt-40 text-center"><h1 className="font-display text-5xl text-ink">Service not found</h1></section> }
